### ISSUE TITLE
Chart rendering time problem and program freezing

### ISSUE THREAD

**Issue by hassan-anari** [Akascape/CTkPieChart#3]
Hello @Akascape,
In my program (CTK), I perform all the processes related to the database, calculations, etc. with using threads.
But when a widget takes a time to render the output, I don't know how to use threads... 
I have 3 pie charts with 12 tags each... The time it takes for the charts to render is about 4 seconds. This rendering time causes my app to freeze for a few seconds... and that's not good at all. What is the solution so that the program does not freeze? I don't have a problem with the rendering time... I just don't know how to use the threads so that the program doesn't freeze.
I hope you understand what I mean... Thanks.

**Comment by Akascape** [comment]
@Nigacatch Sorry for the late reply, you use threading when you are adding values in the pie chart. It's just one line of code, but you have to put all the operations inside a function. Example:
```python
import customtkinter
from CTkPieChart import *
import threading

root = customtkinter.CTk()

def draw_chart():
    pie_chart.add("A", 10)
    pie_chart.add("B", 60, color="cyan", text_color="black")
    pie_chart.add("C", 40)

pie_chart = CTkPieChart(root)
pie_chart.pack()

threading.Thread(target=draw_chart).start()
root.mainloop()
```
